### ISSUE TITLE
Merlin not handling errors in done

### ISSUE THREAD

**Issue by cgallemore** [supercodepoet/django-merlin#2]
Merlin will automatically check for form errors, but if there are problems in the done method where you need to show errors, merlin does not handle the redirect properly.  A good example of this is an issue we had.  We were processing credit card data in our done method, if there was a problem, I was redirecting back to the last step.  The problem here was Merlin was calling self.clear which was clearing all of my session data.

**Comment by supercodepoet** [comment]
Fixed with:

https://github.com/localbase/django-merlin/commit/5d9257e8f41d8146b2331aa1f4376c2778e3e32f
