### ISSUE TITLE
Do you have an example of inserting a new step after the first form is submitted?

### ISSUE THREAD

**Issue by stodge** [supercodepoet/django-merlin#7]
Do you have an example of inserting a new step after the first form is submitted? I can't seem to work it out. Thanks

**Comment by stodge** [comment]
To clarify, I do:

```
(r'^block/create/(?P<slug>[A-Za-z0-9_-]+)$', NewWizard([Step('create-block', CreateBlockForm)])),
```

Which generates and displays the first form just fine. But I don't know what URL to submit to because I want to insert a new form based on the results of the first form's POST.

Thanks

**Comment by stodge** [comment]
Ok so I made some progress but I hit a problem.

I select an option from the first form (step 1)
I insert a second step (form A) dynamically, this form (form A) is displayed ok
I click the back button
I select another option from the first form (step 1 again), but form A is inserted and displayed again

Any ideas how to get around this? Thanks

**Comment by supercodepoet** [comment]
At the point that you add the step you need to make sure the step is not already been added to support the back button.

**Comment by supercodepoet** [comment]
I will work up and example.

**Comment by stodge** [comment]
Of course - that makes perfect sense now you mention it. Thanks!
